import Head from "next/head";
import Header from "../components/Header";

import type { ReactNode } from "react";
interface Props {
  children: ReactNode;
}
export default function Layout({ children }: Props) {
  return (
    <>
      <Header />
      <Head>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className="font- flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#724BDB] to-[#523BF1] pt-6  leading-normal antialiased">
        {children}
      </main>
    </>
  );
}
